# Generated by Django 4.1.7 on 2023-04-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_inventory_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='rem_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store'),
        ),
    ]
